# Generated by Django 5.1.5 on 2025-02-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboro', '0005_imageupload_alter_transactionrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='kind',
            field=models.CharField(choices=[('CHARGE', 'チャージ'), ('USE', '使用')], max_length=10, verbose_name='取引種別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.PositiveIntegerField(default=0, verbose_name='コイン残高'),
        ),
    ]
