# Generated by Django 5.1.5 on 2025-02-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboro', '0006_alter_transactionrecord_kind_alter_user_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='kind',
            field=models.CharField(choices=[('CHARGE', 'チャージ'), ('USE', '使用'), ('CHANGE_PLUS', '修正補填'), ('CHANGE_MINUS', '修正除去')], max_length=20, verbose_name='取引種別'),
        ),
    ]
