# Generated by Django 5.1.5 on 2025-02-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboro', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(choices=[('white', '白'), ('black', '黒')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='custom_setting',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
